services:
  rails:
    container_name: web
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "3000:3000"